name: MacOS Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-tests:
    runs-on: macos-latest

    steps:
      
      - name: Check out code
        uses: actions/checkout@v2

      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV    

      - name: Verify PYTHONPATH
        run: echo $PYTHONPATH

      - name: Run macOS-only test
        run: python test/test_main.py
