name: MacOS Test Workflow

# Trigger the workflow on every push or pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-tests:
    # Specify macOS as the runner
    runs-on: macos-latest

    steps:
      # Check out the code in the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies if you have a requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV    

      # Run your macOS-specific test
      - name: Run macOS-only test
        run: python test/test_main.py
